import type { GroupProjectData } from "../gitlab/types.js";
import type { SectionName } from "./directive.js";

const SECTION_COMPONENT: Record<SectionName, string> = {
  info: "GitlabProjectInfo",
  readme: "GitlabReadme",
  releases: "GitlabReleases",
  issues: "GitlabIssues",
};

/** JSON.stringify yields a valid double-quoted YAML scalar for simple strings. */
function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function renderChildPage(project: GroupProjectData, sections: SectionName[]): string {
  const frontmatter = [
    "---",
    `title: ${yamlString(project.name)}`,
    ...(project.description ? [`description: ${yamlString(project.description)}`] : []),
    "---",
  ].join("\n");

  const body = sections
    .map((s) => `<${SECTION_COMPONENT[s]} project="${project.pathWithNamespace}" />`)
    .join("\n");

  return `${frontmatter}\n{/* AUTO-GENERATED by @ebuildy/docusaurus-plugin-gitlab — do not edit */}\n\n${body}\n`;
}
