import { mkdtempSync, mkdirSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import { writeProjectPages } from "./write.js";

const projects = [
  { id: 1, name: "Web", path: "acme-web", pathWithNamespace: "mygroup/acme-web", slug: "acme-web", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
  { id: 2, name: "Mobile", path: "acme-mobile", pathWithNamespace: "mygroup/team-x/acme-mobile", slug: "team-x/acme-mobile", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
];

function target() {
  return join(mkdtempSync(join(tmpdir(), "glgen-")), "projects");
}

describe("writeProjectPages", () => {
  it("writes marker, gitignore, root category, nested pages, and subgroup category", () => {
    const dir = target();
    writeProjectPages(projects as any, { targetDir: dir, sections: ["readme"], groupLabel: "My Group" });

    expect(existsSync(join(dir, ".gitlab-generated"))).toBe(true);
    expect(readFileSync(join(dir, ".gitignore"), "utf8").trim()).toBe("*");
    expect(JSON.parse(readFileSync(join(dir, "_category_.json"), "utf8")).label).toBe("My Group");
    expect(existsSync(join(dir, "acme-web.mdx"))).toBe(true);
    expect(existsSync(join(dir, "team-x", "acme-mobile.mdx"))).toBe(true);
    expect(JSON.parse(readFileSync(join(dir, "team-x", "_category_.json"), "utf8")).label).toBe("team-x");
    expect(readFileSync(join(dir, "acme-web.mdx"), "utf8")).toContain('<GitlabReadme project="mygroup/acme-web" />');
  });

  it("is idempotent: regenerating removes stale files from a previously-owned dir", () => {
    const dir = target();
    writeProjectPages(projects as any, { targetDir: dir, sections: ["readme"], groupLabel: "G" });
    writeProjectPages([projects[0]] as any, { targetDir: dir, sections: ["readme"], groupLabel: "G" });
    expect(existsSync(join(dir, "acme-web.mdx"))).toBe(true);
    expect(existsSync(join(dir, "team-x", "acme-mobile.mdx"))).toBe(false);
  });

  it("places two projects sharing a subgroup in one dir with a single category file", () => {
    const dir = target();
    const shared = [
      { id: 3, name: "A", path: "a", pathWithNamespace: "mygroup/team-x/a", slug: "team-x/a", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
      { id: 4, name: "B", path: "b", pathWithNamespace: "mygroup/team-x/b", slug: "team-x/b", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
    ];
    writeProjectPages(shared as any, { targetDir: dir, sections: ["readme"], groupLabel: "G" });
    expect(existsSync(join(dir, "team-x", "a.mdx"))).toBe(true);
    expect(existsSync(join(dir, "team-x", "b.mdx"))).toBe(true);
    expect(JSON.parse(readFileSync(join(dir, "team-x", "_category_.json"), "utf8")).label).toBe("team-x");
  });

  it("refuses to overwrite a directory it does not own", () => {
    const dir = target();
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "handwritten.mdx"), "keep me");
    expect(() => writeProjectPages(projects as any, { targetDir: dir, sections: ["readme"], groupLabel: "G" })).toThrow(/not generated by/i);
  });
});
