import { mkdtempSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import { writeProjectPages } from "./write.js";

const projects = [
  { id: 1, name: "Web", path: "acme-web", pathWithNamespace: "mygroup/acme-web", slug: "acme-web", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
  { id: 2, name: "Mobile", path: "acme-mobile", pathWithNamespace: "mygroup/team-x/acme-mobile", slug: "team-x/acme-mobile", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
];

// The target is the declaring page's own folder; seed it with the hand-authored
// index page that the writer must never touch.
function target() {
  const dir = mkdtempSync(join(tmpdir(), "glgen-"));
  writeFileSync(join(dir, "index.mdx"), "# Our projects\n\n{@generateGitlabPages group=1}\n");
  return dir;
}

describe("writeProjectPages", () => {
  it("writes children as siblings, a manifest, and a scoped gitignore — never touching the index page", () => {
    const dir = target();
    writeProjectPages(projects as any, { targetDir: dir, sections: ["readme"] });

    // Hand-authored index page is preserved.
    expect(readFileSync(join(dir, "index.mdx"), "utf8")).toContain("Our projects");
    // Children are written as siblings; the subgroup is mirrored with its category.
    expect(existsSync(join(dir, "acme-web.mdx"))).toBe(true);
    expect(existsSync(join(dir, "team-x", "acme-mobile.mdx"))).toBe(true);
    expect(JSON.parse(readFileSync(join(dir, "team-x", "_category_.json"), "utf8")).label).toBe("team-x");
    expect(readFileSync(join(dir, "acme-web.mdx"), "utf8")).toContain('<GitlabReadme project="mygroup/acme-web" />');
    // No root _category_.json — the declaring page provides the category.
    expect(existsSync(join(dir, "_category_.json"))).toBe(false);
    // Manifest lists generated files; gitignore scopes to them, not the index.
    const manifest = JSON.parse(readFileSync(join(dir, ".gitlab-generated"), "utf8"));
    expect(manifest.files).toContain("acme-web.mdx");
    const ignore = readFileSync(join(dir, ".gitignore"), "utf8");
    expect(ignore).toContain("/acme-web.mdx");
    expect(ignore).toContain("/team-x/");
    expect(ignore).not.toContain("/index.mdx");
  });

  it("is idempotent: regenerating removes stale generated files but keeps the index page", () => {
    const dir = target();
    writeProjectPages(projects as any, { targetDir: dir, sections: ["readme"] });
    writeProjectPages([projects[0]] as any, { targetDir: dir, sections: ["readme"] });
    expect(existsSync(join(dir, "acme-web.mdx"))).toBe(true);
    expect(existsSync(join(dir, "team-x", "acme-mobile.mdx"))).toBe(false);
    expect(existsSync(join(dir, "team-x"))).toBe(false); // empty subgroup dir pruned
    expect(existsSync(join(dir, "index.mdx"))).toBe(true); // author file survives
  });

  it("refuses to overwrite a hand-authored file whose name collides with a project", () => {
    const dir = target();
    writeFileSync(join(dir, "acme-web.mdx"), "hand written");
    expect(() => writeProjectPages(projects as any, { targetDir: dir, sections: ["readme"] })).toThrow(
      /not generated by this plugin/i,
    );
  });

  it("places two projects sharing a subgroup in one dir with a single category file", () => {
    const dir = target();
    const shared = [
      { id: 3, name: "A", path: "a", pathWithNamespace: "mygroup/team-x/a", slug: "team-x/a", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
      { id: 4, name: "B", path: "b", pathWithNamespace: "mygroup/team-x/b", slug: "team-x/b", description: null, webUrl: "", starCount: 0, defaultBranch: "main", topics: [] },
    ];
    writeProjectPages(shared as any, { targetDir: dir, sections: ["readme"] });
    expect(existsSync(join(dir, "team-x", "a.mdx"))).toBe(true);
    expect(existsSync(join(dir, "team-x", "b.mdx"))).toBe(true);
    expect(JSON.parse(readFileSync(join(dir, "team-x", "_category_.json"), "utf8")).label).toBe("team-x");
  });
});
