import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { GroupProjectData } from "../gitlab/types.js";
import type { SectionName } from "./directive.js";
import { renderChildPage } from "./render-page.js";

const MARKER = ".gitlab-generated";

export interface WriteOptions {
  targetDir: string;
  sections: SectionName[];
  /** Label for the root `_category_.json` (e.g. the GitLab group name). */
  groupLabel: string;
}

function writeCategory(dir: string, label: string): void {
  writeFileSync(join(dir, "_category_.json"), `${JSON.stringify({ label }, null, 2)}\n`);
}

/** Ensure every intermediate dir of `slug` exists and carries a `_category_.json`. */
function ensureSlugDirs(targetDir: string, slug: string): void {
  const segments = slug.split("/");
  segments.pop(); // drop the file segment
  let current = targetDir;
  for (const seg of segments) {
    current = join(current, seg);
    if (!existsSync(current)) {
      mkdirSync(current, { recursive: true });
      writeCategory(current, seg);
    }
  }
}

export function writeProjectPages(projects: GroupProjectData[], opts: WriteOptions): string[] {
  const { targetDir } = opts;

  if (existsSync(targetDir)) {
    if (!existsSync(join(targetDir, MARKER))) {
      throw new Error(
        `@ebuildy/docusaurus-plugin-gitlab: refusing to overwrite "${targetDir}" — ` +
          `it was not generated by this plugin (missing ${MARKER}).`,
      );
    }
    rmSync(targetDir, { recursive: true, force: true });
  }
  mkdirSync(targetDir, { recursive: true });
  writeFileSync(join(targetDir, MARKER), "");
  writeFileSync(join(targetDir, ".gitignore"), "*\n");
  writeCategory(targetDir, opts.groupLabel);

  const written: string[] = [];
  for (const project of projects) {
    ensureSlugDirs(targetDir, project.slug);
    const file = join(targetDir, `${project.slug}.mdx`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, renderChildPage(project, opts.sections));
    written.push(file);
  }
  return written;
}
