import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { GroupProjectData } from "../gitlab/types.js";
import type { SectionName } from "./directive.js";
import { renderChildPage } from "./render-page.js";

/** JSON manifest of everything this plugin generated in a target folder. */
const MARKER = ".gitlab-generated";
const GITIGNORE = ".gitignore";

export interface WriteOptions {
  /** The declaring page's own folder; generated pages are written as siblings. */
  targetDir: string;
  sections: SectionName[];
}

interface Manifest {
  /** Files we generated, relative to targetDir (child `.mdx` + subgroup `_category_.json`). */
  files: string[];
  /** Subgroup dirs we created, relative to targetDir. */
  dirs: string[];
}

function readManifest(targetDir: string): Manifest | null {
  const p = join(targetDir, MARKER);
  if (!existsSync(p)) return null;
  try {
    const parsed = JSON.parse(readFileSync(p, "utf8")) as Partial<Manifest>;
    if (Array.isArray(parsed.files) && Array.isArray(parsed.dirs)) {
      return { files: parsed.files, dirs: parsed.dirs };
    }
  } catch {
    // Unreadable/legacy marker → treat as an empty owned manifest.
  }
  return { files: [], dirs: [] };
}

/** Remove everything a previous run generated, without touching hand-authored files. */
function cleanup(targetDir: string, manifest: Manifest): void {
  for (const rel of manifest.files) {
    rmSync(join(targetDir, rel), { force: true });
  }
  // Prune generated subgroup dirs deepest-first, but only if now empty (an author
  // could have added their own files into one).
  for (const rel of [...manifest.dirs].sort((a, b) => b.length - a.length)) {
    const abs = join(targetDir, rel);
    if (existsSync(abs) && readdirSync(abs).length === 0) {
      rmSync(abs, { recursive: true, force: true });
    }
  }
}

/** Build a `.gitignore` that ignores only the generated entries (never the author's index). */
function buildGitignore(manifest: Manifest): string {
  const topFiles: string[] = [];
  const topDirs = new Set<string>();
  for (const f of manifest.files) {
    if (f.includes("/")) topDirs.add(f.slice(0, f.indexOf("/")));
    else topFiles.push(f);
  }
  for (const d of manifest.dirs) topDirs.add(d.slice(0, d.includes("/") ? d.indexOf("/") : d.length));
  const lines = [
    "# @ebuildy/docusaurus-plugin-gitlab — generated files, do not edit",
    `/${MARKER}`,
    `/${GITIGNORE}`,
    ...topFiles.sort().map((f) => `/${f}`),
    ...[...topDirs].sort().map((d) => `/${d}/`),
  ];
  return `${lines.join("\n")}\n`;
}

export function writeProjectPages(projects: GroupProjectData[], opts: WriteOptions): string[] {
  const { targetDir } = opts;
  mkdirSync(targetDir, { recursive: true });

  // Regeneration is idempotent: remove what we generated last time (tracked in the
  // manifest), never the declaring page or other hand-authored files in the folder.
  const previous = readManifest(targetDir);
  if (previous) cleanup(targetDir, previous);

  const files: string[] = [];
  const dirs: string[] = [];
  const written: string[] = [];

  for (const project of projects) {
    // Create each intermediate subgroup dir (mirroring the namespace) with a
    // `_category_.json` labeled by the path segment — only when we create it.
    const segments = project.slug.split("/");
    segments.pop(); // drop the file segment
    let relDir = "";
    let absDir = targetDir;
    for (const seg of segments) {
      relDir = relDir ? `${relDir}/${seg}` : seg;
      absDir = join(absDir, seg);
      if (!existsSync(absDir)) {
        mkdirSync(absDir, { recursive: true });
        dirs.push(relDir);
        const catRel = `${relDir}/_category_.json`;
        writeFileSync(join(targetDir, catRel), `${JSON.stringify({ label: seg }, null, 2)}\n`);
        files.push(catRel);
      }
    }

    const relFile = `${project.slug}.mdx`;
    const abs = join(targetDir, relFile);
    if (existsSync(abs)) {
      throw new Error(
        `@ebuildy/docusaurus-plugin-gitlab: refusing to overwrite "${abs}" — ` +
          `it already exists and was not generated by this plugin.`,
      );
    }
    writeFileSync(abs, renderChildPage(project, opts.sections));
    files.push(relFile);
    written.push(abs);
  }

  const manifest: Manifest = { files, dirs };
  writeFileSync(join(targetDir, MARKER), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(join(targetDir, GITIGNORE), buildGitignore(manifest));
  return written;
}
